maint/check-blocking-todos: Reformat like emacs likes it

diff --git a/maint/check-blocking-todos b/maint/check-blocking-todos
--- a/maint/check-blocking-todos
+++ b/maint/check-blocking-todos
@@ -13,7 +13,15 @@ rc=$?
 set -e
 
 case $rc in
-1)	exit 0;;
-0)	echo >&2 'Found FIXMEs - RC TODS - in the codebase!'; exit 1;;
-*)	echo >&2 'grep failed!'; exit 16;;
+    1)
+	exit 0
+	;;
+    0)
+	echo >&2 'Found FIXMEs - RC TODS - in the codebase!'
+	exit 1
+	;;
+    *)
+	echo >&2 'grep failed!'
+	exit 16
+	;;
 esac
