maint/check-blocking-todos: Fix an error message

diff --git a/maint/check-blocking-todos b/maint/check-blocking-todos
--- a/maint/check-blocking-todos
+++ b/maint/check-blocking-todos
@@ -26,7 +26,7 @@ case "$rcs" in
 	exit 1
 	;;
     *)
-	echo >&2 'grep failed!'
+	echo >&2 'git grep failed!'
 	exit 16
 	;;
 esac
